DrAlzahraniProjects/csusb_fall2024_cse6550_team3

- Dockerfile
- app.py
Fixed docker image name, CMD and port violations
> Fixed docker violations

- Dockerfile
- README.md
- nginx.conf
Changes:
- nginx port changed from 80 to 83 (app available at [localhost:83/team3](http://localhost:83/team3))
- jupyter port changed from 8888 to 6003
> nginx + jupyter ports updated

- Styles/style.css
- app.py
> Added Like/Dislike buttons

- Dockerfile
- app.py
Reverts DrAlzahraniProjects/csusb_fall2024_cse6550_team3#116
> Revert "apache test "

- Dockerfile
- README.md
- app.py
Reverts DrAlzahraniProjects/csusb_fall2024_cse6550_team3#117
> Revert "Revert "apache test ""

- Dockerfile
- README.md
- app.py
Changes:
- Docker run command has a `PROD` env which when set to `PROD=1` does not run jupyter (see README)
- `Dockerfile` clean up
- `app.py` updated to handle `PROD` env
> removed jupyter when deploying to cse server

- Dockerfile
- README.md
- app.py
Changes:
- Removed port 6003
- Removed jupyter code in `app.py`
- Updated docker commands in README
> removed jupyter (for good this time)

- Dockerfile
- app.py
Changes:
- `Dockerfile` uses miniforge and conforms to requirements in syllabus
- `app.py`: subprocess uses run instead of Popen
> updated dockerfile and app,py

- Styles/style.css
- app.py
> Improved 10 stats report

- README.md
Changes:
- Updated the docker run command (for development) to include a volume mount
```
docker run -p 5003:5003 -v $(pwd):/app team3-app
```
- This allows for immediate visibility of code changes without having to rebuild the docker image
Note:
- This won't work on library imports. You have to rebuild the image for that
> added a volume mount

- app.py
I've updated the app.py regarding addition of generating response spinner.
> Added Generating response spinner

- .gitignore
- inference.py
Changes:
- Updated the prompt to be more robust
- Fixed an issue where citations were 1 page behind. 
- Fixed an issue where the links for citation 5 or above was broken
> Better prompt and citation fixed

- app.py
- inference.py
streamed the response by yielding chunks
> Added response streaming

- backend/statistics.py
- frontend/streamlit.py
- requirements.txt
Reverts DrAlzahraniProjects/csusb_fall2024_cse6550_team3#197
> Revert "common_topics or keywords"

- backend/statistics.py
- frontend/streamlit.py
- frontend/styles/style.css
- requirements.txt
Changes:
- Fixed merge issues with `Thrinethra_keywords` branch and `main`
- Updated styles.css
> Common topics features

- README.md
Changes:
- Fixed .env example
- Added an alternative command for docker run (for windows users)
> Fixing errors in README

- backend/citations.py
- backend/document_loading.py
- backend/inference.py
- requirements.txt
Updated how the application does retreival
Change:
- Added `similarity_search` function that filters retrieved docs using distance (Lower values are better)
- Rewrote `chat_completion` to use above function
Notes:
- This should be paired with keyword search because in some cases there are docs with high distance scores that get filtered out
> Updated retrieval step

- backend/statistics.py
- frontend/utils.py
Added reset button for the confusion matrix and metrics
> Added reset button

- backend/statistics.py
- frontend/streamlit.py
- frontend/styles/style.css
- frontend/utils.py
Changes:
- Updated confusion matrix to discussed layout
- Removed gradient scale
- Confusion matrix and performance metrics is displayed even if values are None
- Feedback caption changes if the question is in baseline_questions
- Updated `reset_confusion_matrix()` so feedback functionality works even if user clicks reset
Note:
- If the question is unanswerable then 
- Pressing a like indicates the chatbot answered the question (False Positive) 
- Pressing unlike indicates the chatbot did not answer the question (True negative)
> Updated evaluation metrics

- frontend/utils.py
Changes:
- Specificity and sensitivity have a color now
> Styling update

- backend/citations.py
- backend/inference.py
- frontend/streamlit.py
Reworked citation functions
Changes:
- Sources are displayed as consecutive numbers. 
- Removed some unnecessary code
> reworked citations

- backend/citations.py
- backend/document_loading.py
- backend/inference.py
Changes:
- Added stricter document filtering (lowered distance threshold to 320)
- Made the model responses more deterministic (reduced temperature value)
> Fixing response and citations (WIP)

- README.md
- backend/citations.py
- backend/document_loading.py
- backend/inference.py
- backend/prompts.py
- backend/statistics.py
- frontend/streamlit.py
- frontend/utils.py
Changes:
- A maximum of 2 citations are returned
- Added two system prompts
- The chatbot says it doesn't know the answer if 0 citations are provided
- Updated QA questions
- Added website links to README
- Updated code in `inference.py` and `statistics.py` to meet QA guidelines
Note:
- Question 4 (How does the agile methodology impact software quality?) and 6 (What is the purpose of a task network in project scheduling?) should be changed
> Response update

- README.md
- app.py
- backend/citations.py
- frontend/streamlit.py
Changes:
- Response returns only 1 citation
- Updated unanswerable questions
> Citations reduced + updated eval questions

- backend/inference.py
- backend/prompts.py
- frontend/questions.py
- frontend/streamlit.py
- frontend/utils.py
Changes:
- When 0 sources return default response
- Updated system prompt
- Removed unused code
- Fixed an error in reset_confusion_matrix()
- Whitespace removed and questions turned into lowercase before comparison
> Updated response

- frontend/streamlit.py
Added rate limiting using time stamps and session
> Added rate limiting for DOS

- backend/document_loading.py
- backend/inference.py
- backend/prompts.py
- frontend/streamlit.py
- frontend/utils.py
Changes:
- Added second llm call to rewrite the prompt
- Increased distance threshold
- Non-eval questions are now used to populate the confusion matrix and performance metrics
- Fixed capitalization in metrics labels
> Improving response (WIP)

- backend/inference.py
- frontend/streamlit.py
Changes
- Confusion matrix only gets updated with feedback from eval questions
> reverted feedback functionality

- backend/guardrails.yml
- backend/inference.py
- backend/prompts.py
- frontend/streamlit.py
Changes
- Updated mistral ai parameters
- Guardrails uses system prompt
- Updated system prompt for rewriting
- Error message updated
- Increased delay before 2nd LLM call
> Improving response

- frontend/streamlit.py
> Added dynamic loading message
